### ISSUE TITLE
Fix internal broken "latest" links (`docsy` branch)

### ISSUE THREAD

**Issue by nate-double-u** [etcd-io/website#216]
When `make check-links` is run on the `docsy` branch, there are a lot of errors around the `latest` link. In `master` we get around this by flagging the link so the checker doesn't look at it, but it's not ideal -- it's best not to change the thing being tested for the benefit of the tester.

[docsy-branch-broken-internal-links.txt](https://github.com/etcd-io/website/files/6300446/docsy-branch-broken-internal-links.txt)

**Comment by chalin** [comment]
I'd consider this a "nice to have" rather than a MVP requirement. That being said, I'd like to suggest that we consider using https://www.npmjs.com/package/dart-linkcheck. I've used this tool on other projects and it is fast and works well. Btw, linkcheck runs over a _deployed_ (local or otherwise) site, not over the generated site files like what htmltest does.

**Comment by nate-double-u** [comment]
fixed in https://github.com/etcd-io/website/pull/227
