### ISSUE TITLE
Why can't I see "Xiang Li’s video" at the v3api's Overview?

### ISSUE THREAD

**Issue by kana112233** [etcd-io/website#265]
https://etcd.io/docs/v3.4/rfc/v3api/
see Xiang Li’s video
[see Xiang Li’s video](https://www.youtube.com/watch?v=J5AioGtEPeQ&t=211s)

**Comment by nate-double-u** [comment]
I'm not sure. It's also unavailable through the web archive (though it was captured)
https://web.archive.org/web/20190113041751if_/https://www.youtube.com/watch?v=J5AioGtEPeQ

**Comment by xiang90** [comment]
I do not really know. I do not have a cope of that either :(

**Comment by nate-double-u** [comment]
I think the fix to this is likely to revise the copy to remove this link. Since it's really a dead link, we should probably remove it from the older pages as well.

Affected files:
* content/en/docs/v2.3/rfc/v3api.md
* content/en/docs/v3.1/rfc/v3api.md
* content/en/docs/v3.2/rfc/v3api.md
* content/en/docs/v3.3/rfc/_index.md
* content/en/docs/v3.4/rfc/v3api.md
