### ISSUE TITLE
Netlify builds failing on simple changes

### ISSUE THREAD

**Issue by nate-double-u** [etcd-io/website#287]
**Problem:**
Netlify builds are failing on simple changes. See PRs https://github.com/etcd-io/website/pull/274, https://github.com/etcd-io/website/pull/286

**Comment by nate-double-u** [comment]
Deploy logs:
* #274: https://app.netlify.com/sites/etcd/deploys/609806163558e20007bf2f52
* #286: https://app.netlify.com/sites/etcd/deploys/60a273d1fa2b610007e6f0e9

**Comment by nate-double-u** [comment]
Both PRs look like simple text changes that shouldn't have broken the build. One commonality between these two PRs is that they both look to have been made using the GitHub web edit system.

**Comment by chalin** [comment]
AFAICT, all preview builds are failing (e.g., I cleared the cache and restarted the build of #288, and it's build is failing too) and this seems to be since the release of Node 14.17.0.

For some reason, prior to v14.17.0 (or maybe it's due to an update in `npm`?), Node/npm made sense of script names of the form `prefoo` and it's pre hook, `preprefoo`. That doesn't work anymore, so the script `preview-build` wasn't getting it's pre hook invoked so the submodules weren't recursively loaded, and so the Bootstrap CSS wasn't being found!
