### ISSUE TITLE
Current link checker can't handle redirects

### ISSUE THREAD

**Issue by chalin** [etcd-io/website#307]
As originally reported in #216, our current link checker can't handle paths like `/docs/latest`, so we temporarily came up with a hack (#227), that consisted of replacing `latest` by `v3.4`. This issue is a reminder to undo that hack and switch to using a better link checker (possibly like https://www.npmjs.com/package/dart-linkcheck).

**Comment by nate-double-u** [comment]
It might be interesting to explore GitHub actions in relation to this as well.

https://github.com/JustinBeckwith/linkinator-action
https://www.npmjs.com/package/linkinator

**Comment by nate-double-u** [comment]
I've tried this three ways, and it seems like both dart linkcheck and linkinator fail as they are getting called as part of the build process -- my guess is that since they're being called as an npm post build process that perhaps the DEPLOY_URL hasn't been set up yet, so they are not actually finding a site to check.

netlify-plugin-checklinks is more disappointing - I temporarily added the plugin to the netlify site, and it works to apoint, when it starts failing existing pages. My guess here is that even though they're getting reported as 404, they're probably actually 429 (too many requests), and are being reported incorrectly. Sadly I can't find a retry setting. (I was getting 429s when i was testing the other methods on the live server.)

I think that linkinator is probably still the best option, but I think it needs to run it after the deployment. I'm not exactly sure how to test GitHub actions, so I'll need to do a bit of research.

https://github.com/marketplace/actions/wait-for-netlify-deployment
https://github.com/JustinBeckwith/linkinator-action

**Comment by chalin** [comment]
Satisfactorily close by #336 for now.
