### ISSUE TITLE
`htmltest` should not be looking at external links in CI pipeline

### ISSUE THREAD

**Issue by nate-double-u** [etcd-io/website#370]
> Looks like the link checker failed

The issue was a link to `github.com/ptabor`, but the link checker wanted `https://github.com/ptabor`.

_Originally posted by @nate-double-u in https://github.com/etcd-io/website/pull/367#issuecomment-856246108_

**Comment by nate-double-u** [comment]
This is likely an [upstream](https://github.com/wjdp/htmltest) issue, as the `.htmltest.yml` has `CheckExternal: false` set, and we're not setting `EnforceHTTPS`.

**Comment by nate-double-u** [comment]
It is odd that in my testing the local check worked, where the netlify run failed (so maybe it isn't upstream, but how we're calling it in our CI)

**Comment by chalin** [comment]
`htmltest` wasn't (and isn't) analyzing external links IMHO. To the checker, `github.com/ptabor` is an _internal_ link (since it doesn't start with http -- i.e, it looks like a _path_ of the form `foo/bar`), which is invalid as such. So it was correct to report an internal link error.

The fix, as you noted, was to prefix the reference with `https://` but not because the checker was expecting that, but because the correct reference is `https://github.com/ptabor`.

**Comment by nate-double-u** [comment]
> `htmltest` wasn't (and isn't) analyzing external links IMHO. To the checker, `github.com/ptabor` is an _internal_ link (since it doesn't start with http -- i.e, it looks like a _path_ of the form `foo/bar`), which is invalid as such. So it was correct to report an internal link error.
> 
> The fix, as you noted, was to prefix the reference with `https://` but not because the checker was expecting that, but because the correct reference is `https://github.com/ptabor`.

I agree with this assessment.
