### ISSUE TITLE
Home page issue in Safari: Near endless div

### ISSUE THREAD

**Issue by tadman** [etcd-io/website#465]
The home page for etcd on Safari has the info box showing as miles high

Is it possible the SVG artwork is sized incorrectly? The sizes are registering as 240x33554408px on my machine (not a typo).

Chrome seems to render correctly, no obvious issues.

> Version 14.1.2 (16611.3.10.1.6) on M1 Mac Mini

---

Edit (@chalin): here's a screenshot from Safari on macOS:

![image](https://user-images.githubusercontent.com/4140793/134003501-5496d10d-d688-43ac-ad27-8e238caa8a17.png)

As @rgrupesh found out, this problem also shows up under iOS 14+.

**Comment by rgrupesh** [comment]
Hello @nate-double-u 

I would like to work on this issue(if available). Any pointers to get started?

**Comment by nate-double-u** [comment]
Thanks @rgrupesh! I'm not sure where or when the bug was introduced, but @chalin's #219 PR should give you a good idea of the files that may be related to it.

**Comment by chalin** [comment]
Oh, I wasn't aware of this issue. Hmm, it rings a bell, but not enough to give on any pointers atm.
Thanks for giving it a try @rgrupesh! And thanks for giving pointers @nate-double-u.

(We don't want this high priority issue to be annoying Mac users much longer, so if you can't pinpoint the problem, I'll also take a look at time some time next week. Thanks again for taking a crack at it!)

**Comment by rgrupesh** [comment]
@chalin 

I thought I could emulate safari on my Ubuntu using wine or some online emulator, but in vain. Wine does not have latest version and all online emulator seems to provide latest version only to  paid members. And, the problem seems to be only on latest version. Is there any workaround ? If no, please have a look at it yourself. 

What I learned so far:
- same issue on iPhone, Mac(using latest version of safari)
- no issue on chrome or Firefox.

**Comment by rgrupesh** [comment]
@chalin 

I can't seem to find origin of the problem. Any thing related to this issue would help.

**Comment by chalin** [comment]
The source of the problem seems to be an SVG rendering bug. Safari gives each of the three **Feature** SVGs a ridiculously large height. Choose any of the images, and inspect it -- you'll see something like this for the computed style properties:

> <img src="https://user-images.githubusercontent.com/4140793/134004491-bd073a51-7b71-45a6-a7f1-d1a8b30ce3ce.png" width=300>

That's a height of 44739220px! While I believe that this is a bug in Safari, I'll be submitting a workaround nonetheless.

**Comment by chalin** [comment]
For the record, the problem reported here also affects Chrome under iOS 14.x.

**Comment by nate-double-u** [comment]
I think Chrome on iOS uses Webkit on iOS, so anything affecting iOS Safari would likely also affect iOS Chrome.
