### ISSUE TITLE
Need more explanation step by step..

### ISSUE THREAD

**Issue by siribathala** [etcd-io/website#531]
I am new to kubernetes and I felt like it is not clear for me to understand.

**Comment by jmhbnz** [comment]
Hey @siribathala - Thanks for your suggestion and sorry it has taken so long for this issue to be looked at, the etcd project has not had enough contributors to respond to all issues.

Unfortunately there isn't enough information in your issue for a contributor to be able to raise a pull request so I'll close this issue as it has been so long since it was opened. If you're still running into problems please consider raising a new issue with specific details of what you feel is missing, or reply here with more detail and I'm happy to consider re-opening this issue 🙏🏻
