### ISSUE TITLE
Flag for config file missing in Documentation v3.5

### ISSUE THREAD

**Issue by Kapitaen-zur-See** [etcd-io/website#549]
Hey,

in the new Documentation for the configuration flags the explanation of how to set a config file is missing:
[content/en/docs/v3.5/op-guide/configuration.md](https://github.com/etcd-io/website/blob/main/content/en/docs/v3.5/op-guide/configuration.md)
in v3.4 it's explained:
https://github.com/etcd-io/website/blob/main/content/en/docs/v3.4/op-guide/configuration.md?plain=1#L9

**Comment by jmhbnz** [comment]
Hey @Kapitaen-zur-See - Thanks for raising this issue and apologies for the delay in this being looked at, the etcd project has not had enough contributors to respond to all issues.

Checking v3.5 docs now there is a brief mention of configuration via file and the link to the example file but in general I agree the configuration file documentation in v3.4 (https://github.com/etcd-io/website/blob/main/content/en/docs/v3.4/op-guide/configuration.md) covers configuration via file more completely than in later documentation versions.

I suggest versions 3.5 and 3.6 are updated to include the content covering `ETCD_CONFIG_FILE` environment variable as part of the configuration file section.

This would be a good first issue for someone attending the upcoming etcd contribfest and wanting to help with docs, otherwise I will raise a pr to fix soon.
