### ISSUE TITLE
V3.x docs

### ISSUE THREAD

**Issue by pgodfrin-nov** [etcd-io/website#567]
Erm - where exactly are the config parameters described? In the v2 docs they are here:
https://etcd.io/docs/v2.3/configuration/

**Comment by jmhbnz** [comment]
@pgodfrin-nov apologies for the delay responding, the project has not had enough maintainers to respond to all issues.

You have likely found this since opening this issue but flags are now documented here: https://etcd.io/docs/v3.5/op-guide/configuration

@ahrtr , @spzala I think this one can be closed now.
