### ISSUE TITLE
Alter the documentation for the quota-backend-bytes variable

### ISSUE THREAD

**Issue by necatican** [etcd-io/website#585]
Hello,
Sorry to be nitpicky; I think there's room for misunderstanding in the current documentation.

The current [documentation](https://etcd.io/docs/v3.6/dev-guide/limit/#storage-size-limit) declares that the default value for the `--quota-backend-bytes` is 2GB, but when I look at the [default value](https://github.com/etcd-io/etcd/blob/main/server/storage/quota.go#L31-L34=), it's equal to 2GiB. Usually, this should not be an issue, but it might be best to be verbose since this value is in bytes.

Another issue with this variable is in the [configuration flags page](https://etcd.io/docs/v3.6/op-guide/configuration/). It would be better to declare what "low space quota" means.

`(0 defaults to low space quota).`

I will create a PR with my suggested changes. :) 
Thanks for the project!

**Comment by jmhbnz** [comment]
The open pull request  does not address all documentation versions and unfortunately it has been some time since it was opened so it is unlikely the original submitter will be able to update.

Applying the fix to other documentation versions would be a good first issue for someone at the upcoming contribfest that wants to contribute to improving docs.

**Comment by shayyxi** [comment]
I can work on this.

**Comment by jmhbnz** [comment]
Completed via #665 and #667, thanks @shayyxi
