### ISSUE TITLE
Documentation first page need st like "What is etcd ?" 

### ISSUE THREAD

**Issue by jadjay** [etcd-io/website#631]
Maybe a page explaining the *"pilosophy"* behind etcd:

- how it works, 
- what are the motives,
- what problems etcd solves
- ...

Just my #2cents reflexion, when I get to it.

Thanks for attention,

regards,

**Comment by jmhbnz** [comment]
Hey @jadjay - Many thanks for raising this suggestion and apologies it's taken a while for anyone to respond to this issue, the etcd project has not had enough contributors to respond to all issues.

In terms of a "philosophy" / "why" page we do actually have one, it's just a couple clicks to get through to it, the page that I am talking about is:  https://etcd.io/docs/v3.5/learning/why 

I'm going to close this issue because we do have that page available however if there is a specific area you think the website doesn't cover please reply here and let me know as I'm happy to consider re-opening this, thanks!
