### ISSUE TITLE
Stack overflow not accepting etcd questions

### ISSUE THREAD

**Issue by tdudgeon** [etcd-io/website#680]
Stack overflow is the recommended way to get support. See: https://etcd.io/community/

But Stack overflow are not accepting questions like this as they are not related to programming. See https://stackoverflow.com/questions/76228295/can-i-recover-etcd-from-the-db-file

**Comment by jmhbnz** [comment]
Thanks for reporting this @tdudgeon.  If the question is code related then stackoverflow is a good place to ask, if it's more infrastructure related then [serverfault](https://serverfault.com/search?q=etcd) might be something we could direct folks to.

I'm conscious that we also now request questions to be raised as discussions on the main etcd repository, refer: https://github.com/etcd-io/etcd/discussions

@ahrtr Can you please clarify if github discussions is now our preferred channel for questions instead of stackoverflow? I can raise a change for the community page to reflect this if so, let me know what you think.

**Comment by ahrtr** [comment]
> @ahrtr Can you please clarify if github discussions is now our preferred channel for questions instead of stackoverflow?

I don't think we have extra bandwidth to answer questions on stack overflow.  

Could anyone help me to understand why the question was closed because it's regarded as is not about programming or software development? Obviously the questions is about programming or software development.

**Comment by jmhbnz** [comment]
>Could anyone help me to understand why the question was closed because it's regarded as is not about programming or software development? Obviously the questions is about programming or software development.

I believe mods closed it because they don't see the question about code / software development and more about operating an etcd cluster which I can understand is perhaps better suited for [serverfault](https://serverfault.com/search?q=etcd)?  Just a guess.

The question for me is why do we promote people to go ask question on stack overflow if they are getting their questions shut down and we don't even look at them?  I'm thinking we should just update the website to suggest people post their questions as github discussions instead, at least then we have a chance at maybe looking at it?

**Comment by ahrtr** [comment]
> I'm thinking we should just update the website to suggest people post their questions as github discussions instead, at least then we have a chance at maybe looking at it?

thx. I have no objection on this.
