### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by SeniorJC** [etcd-io/website#688]
This:
compare it’s persistent 

should be:
compare its persistent

https://etcd.io/docs/v3.5/op-guide/data_corruption/

There are other occurrences on the same page, so I suggest searching your site for all occurrences.

**Comment by jmhbnz** [comment]
Hi @SeniorJC - Thanks for raising this, we welcome new contributors so please feel free to raise a pull request with the fix.  Can you please update your message above to include the page url?

**Comment by anand346** [comment]
Please assign this issue to me , I would love to solve it

**Comment by jmhbnz** [comment]
@anand346 thanks for volunteering to help, I will wait to see if @SeniorJC has an interest in fixing it given they raised the issue. If not I'm happy to assign it to you 🙂

**Comment by SeniorJC** [comment]
It seems I do not know how to do pull requests. I returned to the page, clicked **Edit page** and it suggested I do something with a fork. I had only a spoon, but tried to fork anyhow. It told me it was already forked, so I gave up.

I added the page URL, as requested. Glad to help, even if in a tiny way.

**Comment by jmhbnz** [comment]
Hey @SeniorJC - Thanks for adding the link. Here is a quick walk through on the contribution process in general: https://docs.github.com/en/get-started/quickstart/contributing-to-projects.

I would encourage you to get more familiar with `git` so that you would be able to contribute to an upstream project like etcd, there is a lot of learning and training material available for free online around this for example https://docs.github.com/en/get-started/quickstart/git-and-github-learning-resources.

@anand346 - I have assigned this issue to you, let me know if you have any questions.

**Comment by jmhbnz** [comment]
Original pr was not completed, this issue is open for a new contributor.

**Comment by jmhbnz** [comment]
Closing as completed in #722
