### ISSUE TITLE
Add GitHub workflow to keep the releases up to date

### ISSUE THREAD

**Issue by ivanvc** [etcd-io/website#844]
We need to update the latest version manually by updating a commit and then a pull request (in `content/en/docs/{v3.4,v3.5}/_index.md`).

We can automate this and allow a GitHub action to do it for us and just approve a PR.

**Comment by jmhbnz** [comment]
Discussed during sig-etcd triage meeting, the existing workflow is running well, although it would be much nicer to also get the pr raising automatically. We can't do it with GitHub actions due to GitHub enterprise security policies for the K8s GHE org, however we could exploring using the k8s generic autobumper https://docs.prow.k8s.io/docs/components/cli-tools/generic-autobumper for prow.

**Comment by ivanvc** [comment]
Link to #845.

**Comment by ivanvc** [comment]
I was reading Slack's #github-management. It looks like APISnoop was trying to achieve something related. I'm linking to their prow job PR: https://github.com/kubernetes/test-infra/pull/33365, as it may be a good reference for what we need to do.

**Comment by jmhbnz** [comment]
Discussed during sig-etcd triage meeting, the initial efforts are working well and options to add full automation is unlikely at this stage, closing for now. Thanks @ivanvc
