### ISSUE TITLE
versioned documentation

### ISSUE THREAD

**Issue by philips** [etcd-io/website#9]
Like the existing etcd docs website we should have versioned documentation. Copying and/or using the existing docs setup exactly isn't necessary. The only thing is the outcome of the setup: etcd docs that are partitioned by version.

e.g. https://coreos.com/etcd/docs/3.2.13/index.html
v.s. https://coreos.com/etcd/docs/latest/

We can use whatever tooling to accomplish this.  So, if there is another CNCF project doing this you can copy and use that infrastructure.

**Comment by lucperkins** [comment]
A bit of clarification regarding existing blockers (for the sake of all parties involved, especially those who may be able to help):

Currently, the etcd docs are maintained in the [main etcd repo](https://github.com/etcd-io/etcd/tree/master/Documentation) as bare Markdown. Internally at CoreOS (and later Red Hat), a bespoke script written in [Rust](https://rust-lang.org) converts those bare Markdown files into static-site-generator-friendly Markdown, i.e. prefaced with the necessary page metadata to be processed by [Jekyll](https://jekyllrb.com), which is the static site generator used to power the [etcd docs hosted by CoreOS/RedHat](https://coreos.com/etcd/docs/latest/). Without that script, the "raw" Markdown docs can't be "seen" by Jekyll and thus can't be converted into styled HTML.

In order to use the existing etcd documentation in the new site, we need to first get the script working properly (I have not yet succeeded but am working in conjunction with @crawford to get over the hump) and then make the changes necessary to get the Markdown working with [Hugo](https://gohugo.io). This *could* be a relatively simple process (I'll need to get the script working first to determine that) or it could require getting creative. If it were just a matter of a few etcd versions worth of docs, a manual solution might suffice, but unfortunately it's a matter of processing thousands of docs across dozens of versions, so *some* kind of automated solution is going to be necessary.

**Comment by philips** [comment]
I wouldn't get too hung up importing all of the old versions of docs into etcd.io. But, we do need a simple way to handle new versions as releases are cut every few weeks.

**Comment by lucperkins** [comment]
@philips That part is fortunately much easier and essentially already in place (as I can add the appropriate document metadata, which will be carried over into all future releases). The question at this point: do you want to keep the documentation content in this repo or in the main project repo?

**Comment by philips** [comment]
I think keeping the docs in the main repo is fine.

How does the metadata system work? Is that documented somewhere?

**Comment by lucperkins** [comment]
@philips Page metadata looks like this:

```markdown
---
title: Getting Started
description: Run Fluffybird locally on your laptop
foo: bar
---

Here is the actual Markdown content of the page.
```

Without that metadata, static site generators don't even *recognize* Markdown files as "pages" to be rendered. I'm assuming that CoreOS's internal script auto-generates that page metadata for all of the Markdown files in the `Documentation` folder of the main repo, though I haven't yet gotten it to work, so I'm still not certain what the mechanics are.

I can add the necessary metadata to the existing documentation now, which will ensure that we don't need to apply it via any external script going forward.

**Comment by philips** [comment]
How do you plan on having versioned docs? In the CoreOS docs setup
everytime we made a release of etcd a script would copy the docs into the
coreos.com website repo.

**Comment by lucperkins** [comment]
@philips There are two possible scenarios:

1. **Docs are kept in etcd-io/etcd** --- The etcd repo gets pulled into this one as a Git submodule. A script can iterate through a list of versions and copy the `Documentation` folder into `content/docs/<version>` based on the tag.
2. **Docs are kept in this repo** --- Each version is simply a subfolder in `content/docs` (not the most elegant solution but in my experience by far the least troublesome one). Adding a new version just  means copying and pasting the previous "latest" folder.

In both cases, any "latest" logic in the URL, i.e. `/docs/1.1` vs. `/docs/1.2`, can be handled via auto-generated [Netlify redirects](https://www.netlify.com/docs/redirects/). I've done this for several sites and it works great.

**Comment by philips** [comment]
The submodule thing makes sense to me.

Thanks for the clarification.

**Comment by philips** [comment]
@lucperkins I was thinking about it further and I think we should patch the docs for all of the currently maintained branches: https://github.com/etcd-io/etcd/blob/master/Documentation/dev-internal/release.md#release-management

WDYT @etcd-io/maintainers-etcd ?

**Comment by jpbetz** [comment]
That sounds right to me.

**Comment by lucperkins** [comment]
@philips FYI I now have [pull requests](https://github.com/etcd-io/etcd/pulls/lucperkins) open to the etcd-io/etcd project with upstream changes to the `Documentation` folder and the [in-progress site](https://etcd.netlify.com/docs/v3.3.12/) now includes the latest versions of the 3.1, 3.2, and 3.3 series.

**Comment by philips** [comment]
Great! Sorry, I just noticed this PR:
https://github.com/etcd-io/etcd/pull/10615

Do you still need help with that?

**Comment by lucperkins** [comment]
@philips Yeah, I could use a little help there, particularly from someone who's knowledgeable about the intention behind the CI checks

**Comment by philips** [comment]
Oh, I guess the last thing we really need is a warning if you are browsing an out of date doc.

**Comment by philips** [comment]
@hexfusion do you have time to look into this? I keep meaning to but it keeps slipping off of my todo list.
