### ISSUE TITLE
Broken links 

### ISSUE THREAD

**Issue by spzala** [etcd-io/website#90]
While switching to a different version in some cases, the resulting link gives 404 error. 
For example, try to open any version (e.g. v3.4.0) from https://etcd.io/docs/v2/backward_compatibility/ The resulting link https://etcd.io/docs/v3.4.0/backward_compatibility/ is broken. 

/cc @nate-double-u

**Comment by nate-double-u** [comment]
I think this may be due to some pages that have been removed between v2 and v3.

I wonder if there is a better way of handling this 404 in these cases.

We may also want to look into some sort of link checking system generally to try to automate catching these.

**Comment by nate-double-u** [comment]
Netlify looks like it supports 404s based on path:
https://docs.netlify.com/routing/redirects/redirect-options/#custom-404-page-handling

**Comment by nate-double-u** [comment]
Related issue: https://github.com/etcd-io/website/issues/87

**Comment by nate-double-u** [comment]
> I think this may be due to some pages being removed, or moved, between v2 and v3.

We could put together a UX solution to this -- right now we have a menu bar of all the versions, I'm thinking that if there isn't a page available in a given version that version's box gets greyed out. If clicked, it would bring you to that version's root page. The drop down menu should probably also bring the reader to that version's root page (rather than the 404).
